podTemplate(yaml: '''
            apiVersion: v1
            kind: Pod
            spec:
                containers:
                    - name: centos
                      image: centos
                      command:
                        - sleep
                      args:
                        - 99d
                    - name: gradle
                      image: gradle:jdk8
                      command:
                        - sleep
                      args:
                         - 99d
                    - name: cloud-sdk
                      image: google/cloud-sdk
                      command:
                        - sleep
                      args:
                        - 9999999
                      volumeMounts:
                         - name: shared-storage
                           mountPath: /mnt
                restartPolicy: Never
                volumes:
                  - name: shared-storage
                    persistentVolumeClaim:
                      claimName: jenkins-pv-claim
''') {
    node(POD_LABEL) {
        stage ('Staging env test') {
            try {    
                stage('Deploy to Staging') {
                    container('centos') {
                        git 'https://github.com/anandka2000/umldevops.git'
                        stage('start calculator') {
                            sh '''
                            cd week9/ex2/
                            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                            chmod +x ./kubectl
                            ./kubectl get pods 
                            ./kubectl apply -f ./hazelcast.yaml
                            ./kubectl apply -f ./calculator.yaml
                            sleep 30
                            ./kubectl get pods 
                            cd 
                            '''
                        }
                    }
                }
                stage ('Staging test') {
                    container('gradle') {
                        git 'https://github.com/anandka2000/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
                        stage('acceptance test') {
                            sh '''
                            cd Chapter09/sample1/
                            test $(curl calculator-service:8080/sum?a=6\\&b=2 2>/dev/null) -eq 8 && echo 'pass' || echo 'fail'
                            test $(curl calculator-service:8080/div?a=6\\&b=2 2>/dev/null) -eq 3 && echo 'pass' || echo 'fail'
                            [ "$(curl calculator-service:8080/div?a=6\\&b=0 2>/dev/null)" = "Division by 0" ] && echo 'pass' || echo 'fail'
                            '''
                        }
                    } 
                }
            } catch (Exception E) {
                error ('staging tests failed')
            } // catch
        } //end staging
 
        stage ('Deploy to production') {
            container('centos') {
                git 'https://github.com/anandka2000/umldevops.git'
                stage('start calculator') {
                    sh '''
                    cd week9/ex2/
                    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                    chmod +x ./kubectl
                    ./kubectl get pods 
                    ./kubectl apply -f ./hazelcast.yaml
                    ./kubectl apply -f ./calculator.yaml
                    sleep 30
                    ./kubectl get pods 
                    cd 
                    '''
                }
            }
        } // deploy to prod
    } // POD Label
}
