podTemplate(yaml: '''
            apiVersion: v1
            kind: Pod
            spec:
                containers:
                    - name: centos
                      image: centos
                      command:
                        - sleep
                      args:
                        - 99d
                    - name: gradle
                      image: gradle:jdk8
                      command:
                        - sleep
                      args:
                         - 99d
                restartPolicy: Never
''') {
    node(POD_LABEL) {
        stage('k8s') {
            git 'https://github.com/anandka2000/umldevops.git'
            container('centos') {
                stage('start calculator') {
                    sh '''
                    cd week9/ex1/
                    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                    chmod +x ./kubectl
                    ./kubectl get pods 
                    ./kubectl apply -f ./hazelcast.yaml
                    ./kubectl apply -f ./calculator.yaml
                    sleep 30
                    ./kubectl get pods 
                    cd 
                    '''
                    
                }
            }
        }
        stage ('Run test') {
            git 'https://github.com/anandka2000/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
            container('gradle') {
                stage('acceptance test') {
                    sh '''
                    cd Chapter09/sample1/
                    test $(curl calculator-service:8080/sum?a=6\\&b=2 2>/dev/null) -eq 8 && echo 'pass' || echo 'fail'
                    test $(curl calculator-service:8080/div?a=6\\&b=2 2>/dev/null) -eq 3 && echo 'pass' || echo 'fail'
                    [ "$(curl calculator-service:8080/div?a=6\\&b=0 2>/dev/null)" = "Division by 0" ] && echo 'pass' || echo 'fail'
                    '''
                }
            } 
        }
    }
}
