podTemplate(yaml: '''
            apiVersion: v1
            kind: Pod
            spec:
                    - name: gradle
                      image: gradle:jdk8
                      command:
                        - sleep
                      args:
                         - 99d
                restartPolicy: Never
''') {
    node(POD_LABEL) {
        stage ('Run test') {
            git 'https://github.com/anandka2000/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
            container('gradle') {
                stage('acceptance test') {
                    try {
                        sh '''
        	                pwd
                            cd Chapter09/sample3
                            chmod +x ./gradlew
                            ./gradlew acceptanceTest -Dcalculator.url=http://calculator-service:8080
                        '''
                    } catch (Exception E) {
                        echo 'Failure detected'
                    }

                    // from the HTML publisher plugin
                    // https://www.jenkins.io/doc/pipeline/steps/htmlpublisher/
                    publishHTML (target: [
                        reportDir: 'build/reports/tests/acceptanceTest/',
                        reportFiles: 'index.html',
                        reportName: "Acceptance Test Report"
                    ])
                } // test stage
            } //gradle
        } // Run acceptance test
    }//node
}//topmost
